---
- name: install packages
  include_tasks: packages.yml

- name: app directory created
  file:
    state: directory
    path: "{{ app_directory }}"
  become: yes

- name: frontend user created
  user:
    name: "{{ frontend_user }}"
    state: present
    home: "{{ frontend_home }}"
    system: yes
  become: yes

- name: new npm version installed
  npm:
    name: npm
    path: "{{ frontend_home }}"
    state: latest
    global: no
  become_user: "{{ frontend_user }}"
  become: yes

- name: app cloned
  git:
    repo: "{{ frontend_repo }}"
    dest: "{{ frontend_app_dest }}"
    version: "{{ frontend_version }}"
    force: yes
  become_user: "{{ frontend_user }}"
  become: yes
  notify: npm_dependencies

- name: frontend systemd service file added
  template:
    src: frontend_service.j2
    dest: "{{ frontend_service_path }}"
  become: yes
  notify: frontend_service
